export * from "./DynamicHead";
export type { MetaTags, StructuredData } from "./DynamicHead.types";

// schemas
export { videoObject }             from "./schemas/VideoObject";
export { vacationRental }          from "./schemas/VacationRental";
export { paywalledContent }        from "./schemas/PaywalledContent";
export { speakable }               from "./schemas/Speakable";
export { softwareApplication }     from "./schemas/SoftwareApplication";
export { reviewSnippet }           from "./schemas/ReviewSnippet";
export { recipe }                  from "./schemas/Recipe";
export { qaPage }                  from "./schemas/QAPage";
export { profilePage }             from "./schemas/ProfilePage";
export { product }                 from "./schemas/Product";
export { quiz }                    from "./schemas/Quiz";
export { organization }            from "./schemas/Organization";
export { movie }                   from "./schemas/Movie";
export { mathSolver }              from "./schemas/MathSolver";
export { localBusiness }           from "./schemas/LocalBusiness";
export { jobPosting }              from "./schemas/JobPosting";
export { imageObject }             from "./schemas/ImageObject";
export { faqPage }                 from "./schemas/FaqPage";
export { event }                   from "./schemas/Event";
export { employerAggregateRating } from "./schemas/EmployerAggregateRating";
export { educationQAPage }         from "./schemas/EducationQAPage";
export { discussionForumPosting }  from "./schemas/DiscussionForumPosting";
export { dataset }                 from "./schemas/Dataset";
export { course }                  from "./schemas/Course";
export { carousel }                from "./schemas/Carousel";
export { breadcrumbList }          from "./schemas/Breadcrumb";
export { article }                 from "./schemas/Article";